// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "transmitter-artemis/entity"

	mock "github.com/stretchr/testify/mock"
)

// OutboundRepository is an autogenerated mock type for the OutboundRepository type
type OutboundRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, clientData, outboundMessage
func (_m *OutboundRepository) Save(ctx context.Context, clientData entity.ClientData, outboundMessage entity.OutboundMessage) error {
	ret := _m.Called(ctx, clientData, outboundMessage)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ClientData, entity.OutboundMessage) error); ok {
		r0 = rf(ctx, clientData, outboundMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOutboundRepository creates a new instance of OutboundRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboundRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboundRepository {
	mock := &OutboundRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
